version: '3'

services:

  app:
    build: .
    depends_on:
      - redis
      - db
      - nginx
    volumes:
      - ./:/usr/src/project
    environment:
      - NODE_ENV=production
      - EGG_SERVER_ENV=production
      - docker_db=db
      - docker_redis=redis
    ports:
      - "7001:7001"
    restart: always  

  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"  
    restart: always    
    
  db:
    image: mongo # 镜像:版本
    volumes:
      - ./data/db:/data/db
      - ./docker-config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./docker-config/mongo.conf:/etc/mongo.conf
      - ./docker-config/keyfile:/data/keyfile
    command: mongod --auth --keyFile /data/keyfile/mongoReplSet-keyfile --bind_ip_all --replSet rs0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # 默认开启授权，并创建超管用户 mongo -u godis -p godis@admin --authenticationDatabase admin
      - MONGO_INITDB_ROOT_PASSWORD=123456 # 超管密码
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    restart: always

  adminmongo:
    image: mrvautin/adminmongo
    depends_on:
      - db
    volumes:
      - ./docker-config/adminmongo.json:/app/user/config/app.json
      - ./data/backups:/app/user/backups
    ports:
      - "1234:1234"
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./docker-config/conf.d/:/etc/nginx/conf.d/:ro
    ports:
      - "80:80"
    restart: always