
worker_processes  2;

events {
    worker_connections  1024;
}


http {

   upstream egg-web {
       server 172.17.0.212:7001;
       server egg:7001;
   }

   server {
       listen       80;
        location / {
                proxy_pass http://egg-web;
                proxy_redirect default;
        }
    }

}